---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
color: slate
fullWidth: true
disableCollapse: true
useEqualHeights: true

base: https://homepage.rj-web.org
target: _blank

showStats: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google # google, duckduckgo, bing, baidu, brave or custom

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Top:
    style: row
    columns: 2
    header: false
    Date:
      header: true
    Media Apps:
      header: true
      style: row
      columns: 2    
  Stream:
    style: row
    header: false
