---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/





- search:
    provider: google
    target: _blank



- datetime:
    text_size: 3xl
    locale: pt
    format:
        dateStyle: short
        timeStyle: short
        hour12: false

